
--1. Update SPI of all students from 7.00 to 8.00.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=8.00
WHERE SPI=7


--2. Change city of HETVI from RAJKOT to AHMEDABAD.
SELECT * FROM STUDENT
UPDATE STUDENT
SET CITY='AHMEDABAD'
WHERE STDID=101

--3. Update SPI of DEEP to 9.20 and city to VADODARA.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=9.20 ,CITY='VADODARA'
WHERE  STDID=104
--4. Update SPI of DHARMIK to 8.50.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=8.50
WHERE  STDID=107
--5. Update branch name from COMPUTER to IT.
SELECT * FROM STUDENT
UPDATE STUDENT
SET BRANCH='IT'
WHERE  BRANCH='COMPUTER'
--6. Update branch of RAJ to AUTOMOBILE.
SELECT * FROM STUDENT
UPDATE STUDENT
SET BRANCH='AUTOMOBILE'
WHERE  STDID=102
--7. Update SPI to 7.50 where STDID is between 103 and 107.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=7.50
WHERE  STDID BETWEEN 103 AND 107
--8. Update city of PARAG to MUMBAI.
SELECT * FROM STUDENT
UPDATE STUDENT
SET CITY='MUMBAI'
WHERE  SNAME='PARAG'
--9. Update SPI of RIYA to 6.00.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=6
WHERE  SNAME='RIYA'
--10. Update SPI of SMAIR to 7.20 and branch to ELECTRICAL.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=7.20 ,BRANCH='ELECTRICAL'
WHERE  STDID=109
--11. Give 10% increment in SPI.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=SPI+0.1*SPI
--12. Increase SPI by 20% for all students.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=SPI+0.2*SPI
--13. Increase SPI by 0.50 in all records.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=SPI+0.5
--14. Update branch to 'EC' and SPI to 8.00 and city to Surat where SNAME is KRUNAL.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=8.0 ,CITY='SURAT',BRANCH='EC'
WHERE  STDID=106
--15. Update city to 'RAJKOT' and SPI to 7.00 where branch is CIVIL and stdid is less than 105.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=7 ,BRANCH='CIVIL',CITY='RAJKOT'
WHERE  STDID<105
--16. Update SPI of student with stdid 110 to NULL.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=NULL
WHERE STDID=110
--17. Update branch of VISHAL to NULL.
SELECT * FROM STUDENT
UPDATE STUDENT
SET BRANCH=NULL
WHERE STDID=103
--18. Display names of students whose SPI is NULL.
SELECT SNAME FROM STUDENT
WHERE SPI IS NULL
--19. Display students who have branch assigned.
SELECT SNAME FROM STUDENT
WHERE BRANCH IS NOT NULL

--20. Update student with stdid 108 to name DARSHAN, branch COMPUTER, and SPI 8.50.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SNAME='DARSHAN',BRANCH='COMPUTER',SPI=8.5
WHERE STDID=108
--21. Update city to SURAT where SPI is less than 7.00.
SELECT * FROM STUDENT
UPDATE STUDENT
SET CITY='SURAT'
WHERE SPI<7
--22. Update city to NULL and branch to MECHANICAL where stdid is 109.
SELECT * FROM STUDENT
UPDATE STUDENT
SET CITY=NULL,BRANCH='MECHANICAL'
WHERE STDID=109
--LAB 4 EXTRA
-- 1. Update the SPI of all students with the name 'AMIT' to 8.20.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=8.20
WHERE SNAME='AMIT'
-- 2. Change the city of PRIYA from 'MUMBAI' to 'PUNE'.
SELECT * FROM STUDENT
UPDATE STUDENT
SET CITY='PUNE'
WHERE SNAME='PRIYA'
-- 3. Update the SPI of HARSH to 7.80 and change his city to 'SURAT'.
SELECT * FROM STUDENT
UPDATE STUDENT
SET CITY='SURAT',SPI=7.8
WHERE STDID=111
-- 4. Update the branch name from 'MECH' to 'MECHANICAL'.
SELECT * FROM STUDENT
UPDATE STUDENT
SET BRANCH='MECH'
WHERE BRANCH='MECHANICAL'

-- 5. Change the branch of KAVYA to 'CIVIL'.
SELECT * FROM STUDENT
UPDATE STUDENT
SET BRANCH='CIVIL'
WHERE SNAME='KAVYA'
-- 6. Update the SPI to 9.00 for all students whose STDID is between 110 and 115.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=9
WHERE STDID BETWEEN 110 AND 115
-- 7. Update the city of AYUSH to 'BANGALORE'.
SELECT * FROM STUDENT
UPDATE STUDENT
SET CITY='BANGALORE'
WHERE SNAME='AYUSH'
-- 8. Update the SPI of ANJALI to 8.40 and her branch to 'CHEMICAL'.
SELECT * FROM STUDENT
UPDATE STUDENT
SET BRANCH='CHEMICAL',SPI=8.4
WHERE SNAME='ANJALI'
--9. Give a 5% increment in SPI to all students.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=SPI+0.05*SPI
-- 10. Increase the SPI by 15% only for students belonging to the 'IT' branch.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=SPI+0.15*SPI
WHERE BRANCH='IT'
-- 11. Decrease the SPI by 0.20 for all students who live in 'VADODARA'.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=SPI-0.2*SPI
WHERE CITY='VADODARA'
-- 12. Update the branch to 'MINING', SPI to 6.50, and city to 'JAIPUR' where the student's name is VIKRAM.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=6.5,BRANCH='MINING',CITY='JAIPUR'
WHERE SNAME='VIKRAM'
-- 13. Update the city to 'RAJKOT' and SPI to 7.50 for all students whose branch is 'COMPUTER' and STDID is greater than 105.
 
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=7.5,CITY='RAJKOT'
WHERE BRANCH='COMPUTER'AND STDID>105

-- 14. Deduct 10% from the SPI of any student whose current SPI is greater than 9.00.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=SPI-0.1*SPI
WHERE SPI>9
--15. Update the SPI of the student with STDID 112 to NULL.
SELECT * FROM STUDENT
UPDATE STUDENT
SET SPI=NULL
WHERE STDID=112
-- 16. Update the city of ROHAN to NULL.
SELECT * FROM STUDENT
UPDATE STUDENT
SET CITY=NULL
WHERE SNAME='ROHAN'
-- 17. Display all details of students whose branch is NULL.
SELECT * FROM STUDENT
WHERE BRANCH IS NULL
-- 18. Display the names and cities of students who have an SPI assigned (is not NULL).
SELECT SNAME,CITY FROM STUDENT
WHERE SPI IS NOT NULL
-- 19. Update the student with STDID 105 to have the name 'MEET', branch 'EC', and SPI 7.90.
SELECT * FROM STUDENT
UPDATE STUDENT
SET BRANCH='EC',SNAME='MEET',SPI=7.9
WHERE STDID=105
-- 20. Update the city to 'AHMEDABAD' and branch to 'DATA SCIENCE' for the student with STDID 120.
SELECT * FROM STUDENT
UPDATE STUDENT
SET BRANCH='DATA SCIENCE',CITY='AHMEDABAD'
WHERE STDID=120
     