SELECT * FROM STUDENT

--6. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS STDID AND RETURNS DETAILS OF THAT STUDENT. 
CREATE FUNCTION FN_GETSTUDENTBYID
(
	@STID INT
)
RETURNS TABLE
AS
RETURN
(
	SELECT * FROM STUDENT
	WHERE STDID = @STID
)
SELECT * FROM FN_GETSTUDENTBYID(104)

--7. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS CITY AND RETURNS STUDENTS WHOSE SPI IS GREATER THAN 7 FROM THAT CITY. 
CREATE FUNCTION FN_GETSTUDENTBYCITY
(
	@CITY VARCHAR(20)
)
RETURNS TABLE
AS
RETURN
(
	SELECT * FROM STUDENT
	WHERE SPI > 7 AND CITY = @CITY 
);
SELECT * FROM FN_GETSTUDENTBYCITY('RAJKOT')

--8. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS BRANCH AND RETURNS STUDENTS WHOSE SPI IS LESS THAN 8 FROM THAT BRANCH. 
CREATE FUNCTION FN_GETSTUDENTBYBRANCH
(
	@BRANCH VARCHAR(20)
)
RETURNS TABLE
AS
RETURN
(
	SELECT * FROM STUDENT
	WHERE SPI < 8 AND BRANCH = @BRANCH
)
SELECT * FROM FN_GETSTUDENTBYBRANCH('COMPUTER')

--9. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS TOPN AND RETURNS TOP N STUDENTS BASED ON SPI. 
CREATE FUNCTION DBO.GETTOPSTUDENTS
(
    @TOPN INT
)
RETURNS TABLE
AS
RETURN
(
    SELECT TOP (@TOPN) STDID,SNAME,CITY,SPI,BRANCH
    FROM STUDENT
    ORDER BY SPI DESC
);
SELECT * FROM DBO.GETTOPSTUDENTS(5);


--10. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS BRANCH AND RETURNS HIGHEST SPI STUDENT FROM THAT BRANCH.
CREATE FUNCTION DBO.GET_HIGHEST_SPI_STUDENT
(
    @BRANCH VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT TOP 1 STDID,SNAME,CITY,SPI,BRANCH
    FROM STUDENT
    WHERE BRANCH = @BRANCH
    ORDER BY SPI DESC
);
SELECT * FROM DBO.GET_HIGHEST_SPI_STUDENT('COMPUTER');
