SELECT * FROM STUDENT

--1. CREATE A TABLE VALUED FUNCTION TO DISPLAY ALL STUDENT RECORDS. 
CREATE FUNCTION FN_GETALLSTUDENTS()
RETURNS TABLE
AS
RETURN
(
    SELECT *
    FROM STUDENT
);
SELECT * FROM FN_GETALLSTUDENTS();
--2. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS CITY AND RETURNS ALL STUDENTS FROM THAT CITY. 
CREATE FUNCTION FN_GETSTUDENTSBYCITY
(
    @CITY VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT *
    FROM STUDENT
    WHERE CITY = @CITY
);
SELECT * FROM FN_GETSTUDENTSBYCITY('RAJKOT');
--3. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS BRANCH AND RETURNS ALL STUDENTS OF THAT BRANCH. 
CREATE FUNCTION FN_GETSTUDENTSBYBRANCH
(
    @BRANCH VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT * FROM STUDENT
    WHERE BRANCH = @BRANCH
);
SELECT * FROM FN_GETSTUDENTSBYBRANCH('CIVIL');
--4. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS SPI AND RETURNS STUDENTS WHOSE SPI IS GREATER THAN ENTERED SPI. 
CREATE FUNCTION FN_GETSTUDENTSBYSPI
(
    @SPI DECIMAL(5,2)
)
RETURNS TABLE
AS
RETURN
(
    SELECT * FROM STUDENT
    WHERE SPI > @SPI
);
SELECT * FROM FN_GETSTUDENTSBYSPI(9.00);

--5. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS MIN_SPI AND MAX_SPI AND RETURNS STUDENTS WHOSE SPI LIES BETWEEN GIVEN RANGE.
CREATE FUNCTION FN_GETSTUDENTSBYSPIRANGE
(
    @MIN_SPI DECIMAL(5,2),
    @MAX_SPI DECIMAL(5,2)
)
RETURNS TABLE
AS
RETURN
(
    SELECT * FROM STUDENT
    WHERE SPI BETWEEN @MIN_SPI AND @MAX_SPI
);
SELECT * FROM FN_GETSTUDENTSBYSPIRANGE(5.00, 8.00);