--11. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS CITY AND RETURNS TOTAL STUDENTS FROM THAT CITY. 
CREATE FUNCTION DBO.GET_TOTAL_STUDENTS
(
    @CITY VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT @CITY AS CITY,COUNT(*) AS TOTAL_STUDENTS
    FROM STUDENT
    WHERE CITY = @CITY
);
SELECT * FROM DBO.GET_TOTAL_STUDENTS('RAJKOT');

--12. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS BRANCH AND RETURNS STUDENTS ORDERED BY SPI IN DESCENDING ORDER. 
CREATE FUNCTION DBO.GET_STUDENTS_BY_BRANCH
(
    @BRANCH VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT STDID, SNAME, CITY, SPI, BRANCH
    FROM STUDENT
    WHERE BRANCH = @BRANCH
);
SELECT * FROM DBO.GET_STUDENTS_BY_BRANCH('COMPUTER')
ORDER BY SPI DESC;

--13. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS CITY AND RETURNS TOP 3 STUDENT FROM THAT CITY BASED ON SPI. 
CREATE FUNCTION DBO.GET_TOP3_STUDENTS
(
    @CITY VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT TOP 3 STDID,SNAME,CITY,SPI,BRANCH FROM STUDENT
    WHERE CITY = @CITY
    ORDER BY SPI DESC
);
SELECT * FROM DBO.GET_TOP3_STUDENTS('RAJKOT');

--14. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS STDID AND RETURNS STUDENT RANK BASED ON SPI (RANK). 
CREATE FUNCTION DBO.GET_STUDENT_RANK
(
    @STDID INT
)
RETURNS TABLE
AS
RETURN
(
    SELECT STDID,SNAME,CITY,SPI,BRANCH,RANK() OVER (ORDER BY SPI DESC) AS STUDENT_RANK FROM STUDENT
    WHERE STDID = @STDID
);
SELECT * FROM DBO.GET_STUDENT_RANK(101);

--15. CREATE A TABLE VALUED FUNCTION THAT ACCEPTS BRANCH AND RETURNS STUDENTS HAVING SECOND HIGHEST SPI FROM THAT BRANCH. 
CREATE FUNCTION DBO.GET_SECOND_HIGHEST_SPI
(
    @BRANCH VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT STDID,SNAME,CITY,SPI,BRANCH FROM STUDENT
    WHERE BRANCH = @BRANCH
      AND SPI = (
          SELECT MAX(SPI) FROM STUDENT
          WHERE BRANCH = @BRANCH
            AND SPI < (
                SELECT MAX(SPI) FROM STUDENT
                WHERE BRANCH = @BRANCH
            )
      )
);
SELECT * FROM DBO.GET_SECOND_HIGHEST_SPI('COMPUTER');
