SELECT * FROM EMPLOYEE

CREATE TABLE EMPLOYEE_LOG
(
    LOGID INT IDENTITY(1,1),
    EID INT,
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    CITY VARCHAR(50),
    JOININGYEAR INT,
    OPERATION VARCHAR(10),
    OPERATIONDATE DATETIME
);

--1. CREATE TRIGGER FOR PREVENTING REMOVAL OF EMPLOYEES FROM THE TABLE. 
CREATE TRIGGER TRG_PREVENTEMPLOYEEDELETE
ON EMPLOYEE
INSTEAD OF DELETE
AS
BEGIN
    PRINT 'EMPLOYEE RECORDS CANNOT BE DELETED.';
END;

DROP TRIGGER IF EXISTS TRG_PREVENTEMPLOYEEDELETE;

--2. CREATE INSTEAD OF DELETE TRIGGER TO PREVENT DELETION OF EMPLOYEE RECORDS AND STORE DELETED DATA INTO EMPLOYEE_LOG TABLE.
CREATE TRIGGER TRG_EMPLOYEEDELETELOG
ON EMPLOYEE
INSTEAD OF DELETE
AS
BEGIN
    INSERT INTO EMPLOYEE_LOG
    (
        EID,FIRSTNAME,LASTNAME,CITY,JOININGYEAR,OPERATION,OPERATIONDATE
    )
    SELECT
        EID,FIRSTNAME,LASTNAME,CITY,JOININGYEAR,'DELETE',GETDATE()
    FROM DELETED;

    PRINT 'DELETE OPERATION BLOCKED AND DATA STORED IN EMPLOYEE_LOG.';
END;

--3. CREATE INSTEAD OF TRIGGER TO LOG ALL OPERATIONS ON EMPLOYEE TABLE (INSERT/UPDATE/DELETE) INTO EMPLOYEE_LOG TABLE.
CREATE TRIGGER TRG_EMPLOYEEINSERTUPDATELOG
ON EMPLOYEE
AFTER INSERT, UPDATE
AS
BEGIN

    IF NOT EXISTS (SELECT * FROM DELETED)
    BEGIN
        INSERT INTO EMPLOYEE_LOG
        (
            EID,FIRSTNAME,LASTNAME,CITY,JOININGYEAR,OPERATION,OPERATIONDATE
        )
        SELECT
            EID,FIRSTNAME,LASTNAME,CITY,JOININGYEAR,'INSERT',GETDATE()
        FROM INSERTED;
    END;

    IF EXISTS (SELECT * FROM DELETED)
    BEGIN
        INSERT INTO EMPLOYEE_LOG
        (
            EID,FIRSTNAME,LASTNAME,CITY,JOININGYEAR,OPERATION,OPERATIONDATE
        )
        SELECT
            EID,FIRSTNAME,LASTNAME,CITY,JOININGYEAR,'UPDATE',GETDATE()
        FROM INSERTED;
    END;

END;

--4. CREATE TRIGGER TO BLOCK EMPLOYEES FROM UPDATING THEIR JOININGYEAR AND PRINT MESSAGE ‘EMPLOYEES ARE NOT ALLOWED TO UPDATE THEIR JOINING YEAR’. 
CREATE TRIGGER TRG_PREVENTJOININGYEARUPDATE
ON EMPLOYEE
AFTER UPDATE
AS
BEGIN
    IF UPDATE(JOININGYEAR)
    BEGIN
        ROLLBACK TRANSACTION;

        PRINT 'EMPLOYEES ARE NOT ALLOWED TO UPDATE THEIR JOINING YEAR';
    END;
END;

UPDATE EMPLOYEE
SET JOININGYEAR = 2027
WHERE EID = 101;

--5. CREATE TRIGGER FOR PREVENTING DUPLICATE EMPLOYEE RECORDS HAVING SAME FIRSTNAME, LASTNAME, AND CITY.
CREATE TRIGGER TRG_PREVENTDUPLICATEEMPLOYEE
ON EMPLOYEE
AFTER INSERT, UPDATE
AS
BEGIN
    IF EXISTS
    (
        SELECT FIRSTNAME, LASTNAME, CITY
        FROM EMPLOYEE
        GROUP BY FIRSTNAME, LASTNAME, CITY
        HAVING COUNT(*) > 1
    )
    BEGIN
        ROLLBACK TRANSACTION;

        PRINT 'DUPLICATE EMPLOYEE RECORD IS NOT ALLOWED.';
    END;
END;
