--11. CREATE INSTEAD OF INSERT TRIGGER TO PREVENT INSERTION OF STUDENTS WHOSE SPI IS GREATER THAN 10 OR LESS THAN 0. 
CREATE TRIGGER TRG_PREVENTINVALIDSPI
ON STUDENT
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS
    (
        SELECT 1 FROM INSERTED
        WHERE SPI > 10 OR SPI < 0
    )
    BEGIN
        PRINT 'SPI MUST BE BETWEEN 0 AND 10.';
        RETURN;
    END;

    INSERT INTO STUDENT
    (
        SID,STUDENTNAME,BRANCH,SPI
    )
    SELECT
        SID,STUDENTNAME,BRANCH,SPI
    FROM INSERTED;
END;

--12. CREATE INSTEAD OF UPDATE TRIGGER TO BLOCK STUDENTS FROM CHANGING THEIR BRANCH AFTER ADMISSION. 
CREATE TRIGGER TRG_PREVENTBRANCHUPDATE
ON STUDENT
INSTEAD OF UPDATE
AS
BEGIN
    IF EXISTS
    (
        SELECT 1 FROM INSERTED I
        INNER JOIN DELETED D
            ON I.SID = D.SID
        WHERE ISNULL(I.BRANCH, '') <> ISNULL(D.BRANCH, '')
    )
    BEGIN
        PRINT 'STUDENT BRANCH CANNOT BE CHANGED AFTER ADMISSION.';
        RETURN;
    END;

    UPDATE S
    SET
        S.STUDENTNAME = I.STUDENTNAME,S.BRANCH = I.BRANCH,S.SPI = I.SPI
    FROM STUDENT S
    INNER JOIN INSERTED I
        ON S.SID = I.SID;
END;
GO

--13. CREATE INSTEAD OF DELETE TRIGGER TO MOVE DELETED STUDENT RECORDS INTO STUDENT_LOG TABLE INSTEAD OF PERMANENT DELETION. 
CREATE TRIGGER TRG_STUDENTDELETELOG
ON STUDENT
INSTEAD OF DELETE
AS
BEGIN
    INSERT INTO STUDENT_LOG
    (
        SID,STUDENTNAME,BRANCH,SPI,OPERATION,OPERATIONDATE
    )
    SELECT
        SID,STUDENTNAME,BRANCH,SPI,'DELETE',GETDATE()
    FROM DELETED;

    PRINT 'DELETED STUDENT RECORD MOVED TO STUDENT_LOG.';
END;

--14. CREATE INSTEAD OF UPDATE TRIGGER TO PREVENT UPDATING STUDENT SPI. 
CREATE TRIGGER TRG_PREVENTSPIUPDATE
ON STUDENT
INSTEAD OF UPDATE
AS
BEGIN
    IF EXISTS
    (
        SELECT 1 FROM INSERTED I
        INNER JOIN DELETED D
            ON I.SID = D.SID
        WHERE ISNULL(I.SPI, -1) <> ISNULL(D.SPI, -1)
    )
    BEGIN
        PRINT 'STUDENT SPI CANNOT BE UPDATED.';
        RETURN;
    END;

    UPDATE S
    SET
        S.STUDENTNAME = I.STUDENTNAME,S.BRANCH = I.BRANCH,S.SPI = I.SPI
    FROM STUDENT S
    INNER JOIN INSERTED I
        ON S.SID = I.SID;
END;

--15. CREATE INSTEAD OF UPDATE TRIGGER TO STORE STUDENT BRANCH TRANSFER HISTORY INTO STUDENT_LOG TABLE. 
CREATE TRIGGER TRG_BRANCHTRANSFERHISTORY
ON STUDENT
INSTEAD OF UPDATE
AS
BEGIN
    IF EXISTS
    (
        SELECT 1 FROM INSERTED I
        INNER JOIN DELETED D
            ON I.SID = D.SID
        WHERE ISNULL(I.BRANCH, '') <> ISNULL(D.BRANCH, '')
    )
    BEGIN
        INSERT INTO STUDENT_LOG
        (
            SID,STUDENTNAME,BRANCH,SPI,OPERATION,OPERATIONDATE
        )
        SELECT
            D.SID,D.STUDENTNAME,D.BRANCH,D.SPI,
            'BRANCH TRANSFER FROM ' + D.BRANCH +
            ' TO ' + I.BRANCH,
            GETDATE()
        FROM INSERTED I
        INNER JOIN DELETED D
            ON I.SID = D.SID;
    END;

    UPDATE S
    SET
        S.STUDENTNAME = I.STUDENTNAME,S.BRANCH = I.BRANCH,S.SPI = I.SPI
    FROM STUDENT S
    INNER JOIN INSERTED I
        ON S.SID = I.SID;
END;