--6. CREATE INSTEAD OF INSERT TRIGGER TO PREVENT INSERTION OF DUPLICATE EID IN EMPLOYEE TABLE. 
CREATE TRIGGER TRG_PREVENTDUPLICATEEID
ON EMPLOYEE
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS
    (
        SELECT 1
        FROM INSERTED I
        INNER JOIN EMPLOYEE E
            ON I.EID = E.EID
    )
    BEGIN
        PRINT 'DUPLICATE EID IS NOT ALLOWED.';
        RETURN;
    END;

    INSERT INTO EMPLOYEE
    (
        EID,FIRSTNAME,LASTNAME,CITY,JOININGYEAR,GENDER,DEPARTMENTNAME
    )
    SELECT
        EID,FIRSTNAME,LASTNAME,CITY,JOININGYEAR,GENDER,DEPARTMENTNAME
    FROM INSERTED;
END;

--7. CREATE INSTEAD OF UPDATE TRIGGER TO MAINTAIN COMPLETE EMPLOYEE UPDATE HISTORY INTO EMPLOYEE_LOG TABLE. 
CREATE TRIGGER TRG_EMPLOYEEUPDATEHISTORY
ON EMPLOYEE
INSTEAD OF UPDATE
AS
BEGIN
    -- STORE OLD VALUES IN LOG
    INSERT INTO EMPLOYEE_LOG
    (
        EID,FIRSTNAME,LASTNAME,CITY,JOININGYEAR,GENDER,DEPARTMENTNAME,OPERATION,OPERATIONDATE
    )
    SELECT
        D.EID,D.FIRSTNAME,D.LASTNAME,D.CITY,D.JOININGYEAR,D.GENDER,D.DEPARTMENTNAME,
        'UPDATE - OLD DATA',
        GETDATE()
    FROM DELETED D;

    -- STORE NEW VALUES IN LOG
    INSERT INTO EMPLOYEE_LOG
    (
        EID,FIRSTNAME,LASTNAME,CITY,JOININGYEAR,GENDER,DEPARTMENTNAME,OPERATION,OPERATIONDATE
    )
    SELECT
        I.EID,I.FIRSTNAME,I.LASTNAME,I.CITY,I.JOININGYEAR,.GENDER,I.DEPARTMENTNAME,
        'UPDATE - NEW DATA',
        GETDATE()
    FROM INSERTED I;

    -- PERFORM THE ACTUAL UPDATE
    UPDATE E
    SET
        E.FIRSTNAME = I.FIRSTNAME,E.LASTNAME = I.LASTNAME,E.CITY = I.CITY,E.JOININGYEAR = I.JOININGYEAR,E.GENDER = I.GENDER,E.DEPARTMENTNAME = I.DEPARTMENTNAME
    FROM EMPLOYEE E
    INNER JOIN INSERTED I
        ON E.EID = I.EID;
END;

--8. CREATE INSTEAD OF UPDATE TRIGGER TO PREVENT CHANGING EMPLOYEE EID ONCE RECORD IS CREATED. 
CREATE TRIGGER TRG_PREVENTEIDUPDATE
ON EMPLOYEE
INSTEAD OF UPDATE
AS
BEGIN
    IF EXISTS
    (
        SELECT 1 FROM INSERTED I
        INNER JOIN DELETED D
            ON I.EID <> D.EID
    )
    BEGIN
        PRINT 'EMPLOYEE EID CANNOT BE CHANGED ONCE CREATED.';
        RETURN;
    END;

    UPDATE E
    SET
        E.FIRSTNAME = I.FIRSTNAME,E.LASTNAME = I.LASTNAME,E.CITY = I.CITY,E.JOININGYEAR = I.JOININGYEAR,E.GENDER = I.GENDER,E.DEPARTMENTNAME = I.DEPARTMENTNAME
    FROM EMPLOYEE E
    INNER JOIN INSERTED I
        ON E.EID = I.EID;
END;

--9. CREATE INSTEAD OF INSERT TRIGGER TO BLOCK INSERTION OF EMPLOYEES WITH NULL DEPARTMENT NAME. 
CREATE TRIGGER TRG_PREVENTNULLDEPARTMENT
ON EMPLOYEE
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS
    (
        SELECT 1
        FROM INSERTED
        WHERE DEPARTMENTNAME IS NULL
    )
    BEGIN
        PRINT 'EMPLOYEE WITH NULL DEPARTMENT NAME CANNOT BE INSERTED.';
        RETURN;
    END;

    INSERT INTO EMPLOYEE
    (
        EID,FIRSTNAME,LASTNAME,CITY,JOININGYEAR,GENDER,DEPARTMENTNAME
    )
    SELECT
        EID,FIRSTNAME,LASTNAME,CITY,JOININGYEAR,GENDER,DEPARTMENTNAME
    FROM INSERTED;
END;

--10. CREATE INSTEAD OF UPDATE TRIGGER TO PREVENT UPDATING GENDER COLUMN AFTER EMPLOYEE REGISTRATION.
CREATE TRIGGER TRG_PREVENTGENDERUPDATE
ON EMPLOYEE
INSTEAD OF UPDATE
AS
BEGIN
    IF EXISTS
    (
        SELECT 1 FROM INSERTED I
        INNER JOIN DELETED D
            ON I.EID = D.EID
        WHERE ISNULL(I.GENDER, '') <> ISNULL(D.GENDER, '')
    )
    BEGIN
        PRINT 'EMPLOYEE GENDER CANNOT BE CHANGED AFTER REGISTRATION.';
        RETURN;
    END;

    UPDATE E
    SET
        E.FIRSTNAME = I.FIRSTNAME,E.LASTNAME = I.LASTNAME,E.CITY = I.CITY,E.JOININGYEAR = I.JOININGYEAR,E.GENDER = I.GENDER,E.DEPARTMENTNAME = I.DEPARTMENTNAME
    FROM EMPLOYEE E
    INNER JOIN INSERTED I
        ON E.EID = I.EID;
END;