--10. IMPLEMENT SCALAR FUNCTION TO RETURN EMPLOYEE FULL DETAILS USING EID. 
CREATE OR ALTER FUNCTION EMP_FULL_DETAILS
(
    @EID INT
)
RETURNS VARCHAR(MAX)
AS
BEGIN
    DECLARE @DETAILS VARCHAR(MAX);

    SELECT @DETAILS = (
        SELECT *
        FROM Employee
        WHERE EID = @EID
        FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
    );
    RETURN @DETAILS;
END;
SELECT dbo.EMP_FULL_DETAILS(101);


--11. IMPLEMENT SCALAR FUNCTION TO RETURN HIGHEST SALARY FROM A GIVEN DEPARTMENT. 
CREATE OR ALTER FUNCTION HIGHEST_SALARY
(
    @DEPT VARCHAR(50)
)
RETURNS DECIMAL(10,2)
AS
BEGIN
    DECLARE @SALARY DECIMAL(10,2);
    SELECT @SALARY = MAX(SALARY)
    FROM Employee
    WHERE @DEPT = @DEPT;
    RETURN @SALARY;
END;
SELECT dbo.HIGHEST_SALARY('IT');

--12. IMPLEMENT SCALAR FUNCTION TO COUNT TOTAL EMPLOYEES IN EMPLOYEE TABLE. 
CREATE OR ALTER FUNCTION TOTAL_EMPLOYEES()
RETURNS INT
AS
BEGIN
    DECLARE @COUNT INT;
    SELECT @COUNT = COUNT(*)
    FROM Employee;
    RETURN @COUNT;
END;
SELECT dbo.TOTAL_EMPLOYEES();

--13. IMPLEMENT SCALAR FUNCTION TO FIND TOTAL EXPERIENCE OF EMPLOYEE USING JOININGYEAR. 
CREATE OR ALTER FUNCTION EXPERIENCE
(
    @JOININGYEAR INT
)
RETURNS INT
AS
BEGIN
    RETURN YEAR(GETDATE()) - @JOININGYEAR;
END;
SELECT dbo.EXPERIENCE(2020);

--14. IMPLEMENT SCALAR FUNCTION TO RETURN TOTAL NUMBER OF EMPLOYEES IN A GIVEN DEPARTMENT. 
CREATE OR ALTER FUNCTION DEPT_EMPLOYEES
(
    @DEPT VARCHAR(50)
)
RETURNS INT
AS
BEGIN
    DECLARE @COUNT INT;

    SELECT @COUNT = COUNT(*)
    FROM Employee
    WHERE @DEPT = @DEPT;

    RETURN @COUNT;
END;
SELECT dbo.DEPT_EMPLOYEES('IT');

--15. IMPLEMENT SCALAR FUNCTION TO COUNT TOTAL EMPLOYEES FROM A GIVEN CITY. 
CREATE OR ALTER FUNCTION CITY_EMPLOYEES
(
    @CITY VARCHAR(50)
)
RETURNS INT
AS
BEGIN
    DECLARE @COUNT INT;
    SELECT @COUNT = COUNT(*)
    FROM Employee
    WHERE CITY = @CITY;
    RETURN @COUNT;
END;
SELECT dbo.CITY_EMPLOYEES('Ahmedabad');