--1. IMPLEMENT SCALAR FUNCTION TO RETURN "WELCOME TO DBMS LAB". 
CREATE OR ALTER FUNCTION PRINT_MESSAGE()
RETURNS VARCHAR(50)
AS
BEGIN
	RETURN 'WELCOME TO DBMS LAB';
END;
SELECT dbo.PRINT_MESSAGE() AS Message

--2. IMPLEMENT SCALAR FUNCTION TO CALCULATE SIMPLE INTEREST. 
CREATE OR ALTER FUNCTION SIMPLE_INTEREST
(
	@P DECIMAL(10,2),
	@R DECIMAL(10,2),
	@T DECIMAL(10,2)
)
RETURNS DECIMAL(10,2)
AS
BEGIN
	RETURN (@P*@R*@T)/100;
END;
SELECT dbo.SIMPLE_INTEREST(1000,5,2) 

--3. IMPLEMENT SCALAR FUNCTION TO FIND DIFFERENCE IN DAYS BETWEEN TWO DATES. 
CREATE OR ALTER FUNCTION DIFF_DATE
(
	@SD DATE,
	@ED DATE
)
RETURNS INT
AS
BEGIN
	RETURN DATEDIFF(DAY,@SD,@ED);
END;
SELECT dbo.DIFF_DATE('2008-02-23','2009-02-28')

--4. IMPLEMENT SCALAR FUNCTION TO CHECK WHETHER NUMBER IS ODD OR EVEN. 
CREATE OR ALTER FUNCTION ODD_EVEN
(
	@NUM INT
)
RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @RESULT VARCHAR(20);
	IF(@NUM%2=0)
		SET @RESULT =  'EVEN';
	ELSE
		SET @RESULT = 'ODD';
	RETURN @RESULT
END;
SELECT dbo.ODD_EVEN(25)

--5. IMPLEMENT SCALAR FUNCTION TO PRINT NUMBERS FROM 1 TO N.
CREATE OR ALTER FUNCTION PRINT_NUM
(
	@N INT
)
RETURNS VARCHAR(MAX)
AS
BEGIN
	DECLARE @I INT = 1
	DECLARE @RESULT VARCHAR(MAX) = ' ';
	WHILE(@I <= @N)
	BEGIN
		SET @RESULT = @RESULT + CAST(@I AS VARCHAR) + ' '
		SET @I = @I + 1
	END;
	RETURN @RESULT
END;
SELECT dbo.PRINT_NUM(5)