--6. IMPLEMENT SCALAR FUNCTION TO CALCULATE FACTORIAL OF GIVEN NUMBER. 
CREATE OR ALTER FUNCTION FACTORIAL
(
    @NUM INT
)
RETURNS INT
AS
BEGIN
    DECLARE @I INT = 1;
    DECLARE @ANS INT = 1;
    WHILE @I <= @NUM
    BEGIN
        SET @ANS = @ANS * @I;
        SET @I = @I + 1;
    END;
    RETURN @ANS;
END;
SELECT dbo.FACTORIAL(5);

--7. IMPLEMENT SCALAR FUNCTION TO CHECK PALINDROME NUMBER. 
CREATE OR ALTER FUNCTION PALINDROME
(
    @NUM INT
)
RETURNS VARCHAR(20)
AS
BEGIN
    DECLARE @TEMP INT = @NUM;
    DECLARE @REV INT = 0;
    DECLARE @REM INT
    DECLARE @RESULT VARCHAR(20)
    WHILE @TEMP > 0
    BEGIN
        SET @REM = @TEMP % 10;
        SET @REV = @REV * 10 + @REM;
        SET @TEMP = @TEMP / 10;
    END;
    IF @NUM = @REV
        SET @RESULT = 'PALINDROME';
    ELSE
        SET @RESULT = 'NOT PALINDROME';
        RETURN @RESULT
END;
SELECT dbo.PALINDROME(121);

--8. IMPLEMENT SCALAR FUNCTION TO FIND MAXIMUM OF THREE NUMBERS. 
CREATE OR ALTER FUNCTION MAX_THREE
(
    @A INT,
    @B INT,
    @C INT
)
RETURNS INT
AS
BEGIN
    DECLARE @MAX INT;
    SET @MAX = @A; 
    IF @B > @MAX
        SET @MAX = @B
    IF @C > @MAX
        SET @MAX = @C;
    RETURN @MAX;
END;
SELECT dbo.MAX_THREE(10, 25, 15);

--9. IMPLEMENT SCALAR FUNCTION TO CALCULATE SQUARE AND CUBE OF A NUMBER. 
CREATE OR ALTER FUNCTION SQUARE
(
    @NUM INT
)
RETURNS INT
AS
BEGIN
    RETURN @NUM * @NUM;
END;
SELECT dbo.SQUARE(5);